BEGIN;

CREATE SCHEMA IF NOT EXISTS DBO;

USE DBO;

CREATE TABLE IF NOT EXISTS DBO.USER (
    ID VARCHAR(255),
    NAME VARCHAR(40) NOt NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CREATION_DATE DATE,
    MODIFICATION_DATE DATE,
    LAST_LOGIN_DATE DATE,
    TOKEN VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DBO.PHONE (
    ID VARCHAR(255),
    USER_ID VARCHAR(255),
    NUMBER VARCHAR(60),
    CITY_CODE VARCHAR(10),
    COUNTRY_CODE VARCHAR(5) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DBO.USER_PHONE (
    USER_ID VARCHAR(255),
    PHONE_ID VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

COMMIT;